### ISSUE TITLE
Does it full ConceptNet 5.7?

### ISSUE THREAD

**Issue by koren-v** [ldtoolkit/conceptnet-lite#10]
Hi, I really like this framework, but wanted to ask If it's really a full graph? 

And I found one more project in your repositories - conceptnet-rocks, should I thy that one?

**Comment by rominf** [comment]
Hi Vitaly!

Both: conceptnet-lite and conceptnet-rocks are designed to work with a full graph of ConceptNet >= 5.7.

Here is a summary of the differences between libraries.

conceptnet-lite:
1. Powered by SQLite and peewee.
2. Quite slow (slower than the original ConceptNet library).
3. Documented.
4. There is a pre-built database available.
5. It has its own way of querying.
6. Fully packaged on PyPI.

conceptnet-rocks:
1. Powered by ArangoDB (which is powered by RocksDB). 
2. Quite fast (much faster than conceptnet-lite, faster than the original ConceptNet library).
3. Not documented yet.
4. There is not pre-built database available (you have to download the CSV dump and prepare the database yourself).
5. It's a drop-in replacement for the ConceptNet library in terms of querying.
6. Not packaged on PyPI.

If you decide to invest your time to understand conceptnet-rocks and use it, I would be very gladful if you make a PRs with bug fixes, tests, documentation, etc. I'm planning to improve conceptnet-rocks myself, but unfortunately, I don't have an opportunity right now.

**Comment by koren-v** [comment]
@rominf Thank's for your answer! I saw your repository where you compared the performance of original and rocks, but it seems that I should try it for myself to measure the difference, could you give an approximate comparison, e. g how much faster the rocks is?

**Comment by rominf** [comment]
@koren-v I've made some changes in ConceptNet Rocks, so my benchmark is no longer valid. I'm planning to make the benchmark again.

**Comment by koren-v** [comment]
@rominf Sounds great!) Thanks for your answers! Probably will try ConceptNet Rocks, also it would be great if you will share with results)

**Comment by wangjian026** [comment]
Hi, Thank you for your work, I wonder whether the conceptnet-rocks  supports the same type of query as the conceptnet-lite? such as "Accessing all relations for a given concepts"

**Comment by rominf** [comment]
Hi. Thanks for the interest.

`conceptnet-rocks` and `conceptnet-lite` are incompatible. `conceptnet-rocks` has a `lookup` method which mimics the behavior of according to the method of Python API of original ConceptNet: https://github.com/commonsense/conceptnet5/wiki/API#local-python-api. So, there is no one-liner for "Accessing all relations for a given concepts" you have to either do two queries and merge the results or write a direct query to ArangoDB.

**Comment by rominf** [comment]
ConceptNet upstream is no longer updated, this ConceptNet Lite wrapper won't be updated anymore either.
