### ISSUE TITLE
LanguageDoesNotExist Error

### ISSUE THREAD

**Issue by KushJain473** [ldtoolkit/conceptnet-lite#11]
I am trying to use this package in google collaborator jupyter notebook, but it gives me the following error (For English 'en' language):

`LanguageDoesNotExist: <Model: Language> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name" FROM "language" AS "t1" WHERE ("t1"."name" = ?) LIMIT ? OFFSET ?
Params: ['en', 1, 0]`
This is coming for one of the examples from the documentation which I try to execute:

`from conceptnet_lite import Label

cat_concepts = Label.get(text='cat', language ='en').concepts  
for c in cat_concepts:
    print("    Concept URI:", c.uri)
    print("    Concept text:", c.text)
    print("    Concept language:", c.language.name)`

I have followed the instructions for downloading and connecting to the database using the collect() function, but this error persists. Could you tell me what could be the fix for it?

**Comment by rominf** [comment]
Hi @KushJain473.
Sorry, but I don't have an opportunity to investigate this until the end of this year.

**Comment by rominf** [comment]
I found this issue while doing maintenance work, I am sorry for not replying in time. ConceptNet upstream is no longer updated, this ConceptNet Lite wrapper won't be updated anymore either.
